name: Daily KBO Standings DB Update

on:
  schedule:
    # 매일 한국 시간 자정 (UTC 15:00)에 실행
    # (UTC 기준이므로 한국 시간 00:00은 UTC 15:00입니다)
    - cron: '1 15 * * *' 
  workflow_dispatch:
    # 수동으로 워크플로우를 실행할 수 있도록 허용

jobs:
  crawl_and_update:
    runs-on: ubuntu-latest # GitHub Actions는 Ubuntu 환경에서 실행됩니다.
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # 사용 중인 Python 버전에 맞춰주세요.

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run KBO Standings Crawler and DB Updater
      env:
        # DB_URI는 GitHub Secrets에 등록해야 합니다.
        # GitHub 리포지토리 Settings -> Secrets and variables -> Actions -> New repository secret
        # 이름: DB_URI, 값: mysql+pymysql://root:dugout2025!!@dugout-dev.cn6mm486utfi.ap-northeast-2.rds.amazonaws.com:3306/dugoutDB?charset=utf8
        DB_URI: ${{ secrets.DB_URI }}
      run: |
        python update_team_records.py # DB 적재 스크립트 파일명
